var hierarchy =
[
    [ "com.linkauto.restapi.controller.AuthController", "classcom_1_1linkauto_1_1restapi_1_1controller_1_1AuthController.html", null ],
    [ "com.linkauto.restapi.controller.AuthControllerTest", "classcom_1_1linkauto_1_1restapi_1_1controller_1_1AuthControllerTest.html", null ],
    [ "com.linkauto.restapi.service.AuthService", "classcom_1_1linkauto_1_1restapi_1_1service_1_1AuthService.html", null ],
    [ "com.linkauto.restapi.performance.AuthServicePerformanceTest", "classcom_1_1linkauto_1_1restapi_1_1performance_1_1AuthServicePerformanceTest.html", null ],
    [ "com.linkauto.restapi.service.AuthServiceTest", "classcom_1_1linkauto_1_1restapi_1_1service_1_1AuthServiceTest.html", null ],
    [ "com.linkauto.client.controller.ClientController", "classcom_1_1linkauto_1_1client_1_1controller_1_1ClientController.html", null ],
    [ "com.linkauto.client.controller.ClientControllerTest", "classcom_1_1linkauto_1_1client_1_1controller_1_1ClientControllerTest.html", null ],
    [ "com.linkauto.restapi.model.Comment", "classcom_1_1linkauto_1_1restapi_1_1model_1_1Comment.html", null ],
    [ "com.linkauto.restapi.dto.CommentDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CommentDTO.html", null ],
    [ "com.linkauto.restapi.dto.CommentDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CommentDTOTest.html", null ],
    [ "com.linkauto.restapi.integration.CommentIntegrationTest", "classcom_1_1linkauto_1_1restapi_1_1integration_1_1CommentIntegrationTest.html", null ],
    [ "com.linkauto.restapi.dto.CommentReturnerDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CommentReturnerDTO.html", null ],
    [ "com.linkauto.restapi.dto.CommentReturnerDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CommentReturnerDTOTest.html", null ],
    [ "com.linkauto.restapi.model.CommentTest", "classcom_1_1linkauto_1_1restapi_1_1model_1_1CommentTest.html", null ],
    [ "com.linkauto.restapi.dto.CredencialesDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CredencialesDTO.html", null ],
    [ "com.linkauto.restapi.dto.CredencialesDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1CredencialesDTOTest.html", null ],
    [ "com.linkauto.restapi.model.Event", "classcom_1_1linkauto_1_1restapi_1_1model_1_1Event.html", null ],
    [ "com.linkauto.restapi.dto.EventDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1EventDTO.html", null ],
    [ "com.linkauto.restapi.dto.EventDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1EventDTOTest.html", null ],
    [ "com.linkauto.restapi.dto.EventReturnerDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1EventReturnerDTO.html", null ],
    [ "com.linkauto.restapi.dto.EventReturnerDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1EventReturnerDTOTest.html", null ],
    [ "com.linkauto.restapi.model.EventTest", "classcom_1_1linkauto_1_1restapi_1_1model_1_1EventTest.html", null ],
    [ "com.linkauto.restapi.model.User.Gender", "enumcom_1_1linkauto_1_1restapi_1_1model_1_1User_1_1Gender.html", null ],
    [ "com.linkauto.client.service.ILinkAutoServiceProxy", "interfacecom_1_1linkauto_1_1client_1_1service_1_1ILinkAutoServiceProxy.html", [
      [ "com.linkauto.client.service.ClientServiceProxy", "classcom_1_1linkauto_1_1client_1_1service_1_1ClientServiceProxy.html", null ]
    ] ],
    [ "JpaRepository", null, [
      [ "com.linkauto.restapi.repository.CommentRepository", "interfacecom_1_1linkauto_1_1restapi_1_1repository_1_1CommentRepository.html", null ],
      [ "com.linkauto.restapi.repository.EventRepository", "interfacecom_1_1linkauto_1_1restapi_1_1repository_1_1EventRepository.html", null ],
      [ "com.linkauto.restapi.repository.PostRepository", "interfacecom_1_1linkauto_1_1restapi_1_1repository_1_1PostRepository.html", null ],
      [ "com.linkauto.restapi.repository.UserRepository", "interfacecom_1_1linkauto_1_1restapi_1_1repository_1_1UserRepository.html", null ]
    ] ],
    [ "com.linkauto.restapi.controller.LinkAutoController", "classcom_1_1linkauto_1_1restapi_1_1controller_1_1LinkAutoController.html", null ],
    [ "com.linkauto.restapi.controller.LinkAutoControllerTest", "classcom_1_1linkauto_1_1restapi_1_1controller_1_1LinkAutoControllerTest.html", null ],
    [ "com.linkauto.restapi.service.LinkAutoService", "classcom_1_1linkauto_1_1restapi_1_1service_1_1LinkAutoService.html", null ],
    [ "com.linkauto.restapi.performance.LinkAutoServicePerformanceTest", "classcom_1_1linkauto_1_1restapi_1_1performance_1_1LinkAutoServicePerformanceTest.html", null ],
    [ "com.linkauto.restapi.service.LinkAutoServiceTest", "classcom_1_1linkauto_1_1restapi_1_1service_1_1LinkAutoServiceTest.html", null ],
    [ "com.linkauto.restapi.model.Post", "classcom_1_1linkauto_1_1restapi_1_1model_1_1Post.html", null ],
    [ "com.linkauto.restapi.dto.PostDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1PostDTO.html", null ],
    [ "com.linkauto.restapi.dto.PostDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1PostDTOTest.html", null ],
    [ "com.linkauto.restapi.integration.PostIntegrationTest", "classcom_1_1linkauto_1_1restapi_1_1integration_1_1PostIntegrationTest.html", null ],
    [ "com.linkauto.restapi.dto.PostReturnerDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1PostReturnerDTO.html", null ],
    [ "com.linkauto.restapi.dto.PostReturnerDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1PostReturnerDTOTest.html", null ],
    [ "com.linkauto.restapi.model.PostTest", "classcom_1_1linkauto_1_1restapi_1_1model_1_1PostTest.html", null ],
    [ "com.linkauto.restapi.RestApiApplication", "classcom_1_1linkauto_1_1restapi_1_1RestApiApplication.html", null ],
    [ "com.linkauto.restapi.model.Role", "enumcom_1_1linkauto_1_1restapi_1_1model_1_1Role.html", null ],
    [ "com.linkauto.restapi.dto.ShareReturnerDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1ShareReturnerDTO.html", null ],
    [ "com.linkauto.restapi.dto.ShareReturnerDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1ShareReturnerDTOTest.html", null ],
    [ "com.linkauto.restapi.dto.UpdateUserDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UpdateUserDTO.html", null ],
    [ "com.linkauto.restapi.model.User", "classcom_1_1linkauto_1_1restapi_1_1model_1_1User.html", null ],
    [ "com.linkauto.restapi.dto.UserDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserDTO.html", null ],
    [ "com.linkauto.restapi.dto.UserDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserDTOTest.html", null ],
    [ "com.linkauto.restapi.integration.UserIntegrationTest", "classcom_1_1linkauto_1_1restapi_1_1integration_1_1UserIntegrationTest.html", null ],
    [ "com.linkauto.restapi.dto.UserRegisterDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserRegisterDTO.html", null ],
    [ "com.linkauto.restapi.dto.UserRegisterDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserRegisterDTOTest.html", null ],
    [ "com.linkauto.restapi.dto.UserReturnerDTO", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserReturnerDTO.html", null ],
    [ "com.linkauto.restapi.dto.UserReturnerDTOTest", "classcom_1_1linkauto_1_1restapi_1_1dto_1_1UserReturnerDTOTest.html", null ],
    [ "com.linkauto.restapi.model.UserTest", "classcom_1_1linkauto_1_1restapi_1_1model_1_1UserTest.html", null ],
    [ "com.linkauto.client.WebClientApplication", "classcom_1_1linkauto_1_1client_1_1WebClientApplication.html", null ]
];