# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Wait for MySQL to be ready
      run: |
        for i in {1..10}; do
          if mysqladmin ping -h 127.0.0.1 -uroot -proot --silent; then
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 5
        done

    - name: Run DB initialization script
      run: |
        echo "Running DB setup..."
        mysql -h 127.0.0.1 -uroot -proot < rest-api/src/main/resources/dbsetup.sql

    - name: Unit Test
      run: mvn test

    - name: Run Integration Tests and Verify
      run: |
        mvn -Pintegration integration-test
        mvn failsafe:verify

    - name: Performance Test
      run: |
        mvn -Pperformance integration-test
        mvn failsafe:verify

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Maven Site
      run: mvn site
    
    - name: Copy site doxygen output to docs folder
      run: |
        mkdir -p docs
        rm -rf docs/site
        mkdir -p docs/site
        cp -r target/site/* docs/site/
        mkdir -p docs/site/client
        cp -r client/target/site/* docs/site/client/
        mkdir -p docs/site/rest-api
        cp -r rest-api/target/site/* docs/site/rest-api/
        mkdir -p docs/site/reports
        cp -r rest-api/target/reports/* docs/site/reports/
        rm -rf docs/doxygen
        mkdir -p docs/doxygen
        cp -r doxygen/html/* docs/doxygen/

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: docs
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}